[package]
name = "AptosSwap"
version = "0.1.0"

[addresses]
AptosSwap = "0x11"
CoinAdmin = "0x12"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a615536bdb8a8dedb7ec029ddfbf12b80b64f979"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a615536bdb8a8dedb7ec029ddfbf12b80b64f979"
subdir = "aptos-move/framework/aptos-framework"
addr_subst = { Std = "0x1" }

