[package]
name = "AptosSwap"
version = "0.1.0"

[addresses]
AptosSwap = "0x11"
CoinAdmin = "0x12"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "88091bc88b0da654a1341a389b9b770a63559f25"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { Std = "0x1" }

[dependencies.MoveNursery]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "88091bc88b0da654a1341a389b9b770a63559f25"
subdir = "aptos-move/framework/move-stdlib/nursery"
addr_subst = { Std = "0x1" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "88091bc88b0da654a1341a389b9b770a63559f25"
subdir = "aptos-move/framework/aptos-framework"
addr_subst = { Std = "0x1" }

