[package]
name = 'LiquidswapLP'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0xe52dc83080dc7602f8c4a3ca51eaa582cd0f0901bbae6ca870c83967906f8d03"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "d49e0929c986af1b0e8eef612c4cd0282443bdc6"
subdir = "aptos-move/framework/move-stdlib"

