name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - releases-v*
    tags:
      - v*

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          prover: true

      - name: Build
        run: aptos move compile

      - name: Test Liquidswap
        run: aptos move test

      - name: Test LiquidswapRouterV2
        run: aptos move test --package-dir ./liquidswap_router_v2

      - name: Prove math.move
        run: aptos move prove --filter math
